
server:
  port: 8080

spring:
  application:
           name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://payment-postgres:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect


