
server:
  port: 8080

spring:
  application:
          name: registration-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://registration-postgres:5432/registrationdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect




